extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
  comments:
    min-spaces-from-content: 1
    ignore: |
      /cloud-init/user-data.example.yml
      /examples/pi-imager/user-data.example.yml
