---
name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Include logs and steps to reproduce.
    validations:
      required: true
