---
name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: what
    attributes:
      label: What would you like to see?
      description: Explain the change and why.
    validations:
      required: true
