#cloud-config
---
# Example Pi Imager user-data.
# Copy/adjust for your environment.

write_files:
  - path: /etc/kiosk-retropie/config.env
    permissions: "0644"
    content: |
      # Required (flashing/cloud-init bootstrap)
      # Pin to a tag/commit for deterministic installs.
      KIOSK_RETROPIE_REPO_URL=https://github.com/theaussiepom/kiosk-retropie.git
      KIOSK_RETROPIE_REPO_REF=main

      # Optional: where to clone to
      # KIOSK_RETROPIE_CHECKOUT_DIR=/opt/kiosk-retropie

      # Required (kiosk)
      KIOSK_URL=

      # Optional: display
      # Rotation: normal | left | right | inverted
      # KIOSK_SCREEN_ROTATION=normal

      # Xorg virtual terminals (VTs) used by kiosk vs Retro mode
      # KIOSK_X_VT=7
      # RETROPIE_X_VT=8

      # Chromium profile directory (cookies, local storage, cache, preferences).
      # Must be writable by the user running the kiosk service.
      # KIOSK_CHROMIUM_PROFILE_DIR=/var/lib/kiosk-retropie/chromium-profile

      # Optional: ROM sync from NFS (read-only)
      # Required to enable:
      # NFS_SERVER=192.168.1.20
      # NFS_ROMS_PATH=/export/retropie
      # Optional:
      # RETROPIE_NFS_MOUNT_POINT=/mnt/kiosk-retropie-roms
      # RETROPIE_NFS_MOUNT_OPTIONS=ro

      # Optional: periodic save backup to NFS (skips while in Retro mode)
      # RETROPIE_SAVE_BACKUP_ENABLED=0
      # NFS_SAVE_BACKUP_PATH=/export/kiosk-retropie-backups
      # RETROPIE_SAVE_BACKUP_DIR=/mnt/kiosk-retropie-backup
      # RETROPIE_SAVE_BACKUP_SUBDIR=kiosk-retropie-saves
      # RETROPIE_SAVE_BACKUP_DELETE=0
      # RETROPIE_SAVE_BACKUP_NFS_MOUNT_OPTIONS=rw

      # Optional: MQTT bridges (LEDs and/or screen brightness)
      # Broker settings (required if any MQTT bridge is enabled)
      # MQTT_HOST=192.168.1.50
      # MQTT_PORT=1883
      # MQTT_USERNAME=
      # MQTT_PASSWORD=
      # MQTT_TLS=0

      # Root topic prefix for all MQTT topics (use a unique prefix per device if you run multiple kiosks)
      # KIOSK_MQTT_TOPIC_PREFIX=kiosk-retropie

      # LED MQTT bridge
      # KIOSK_LED_MQTT_ENABLED=0
      # KIOSK_LED_MQTT_POLL_SEC=2

      # Screen brightness MQTT bridge
      # KIOSK_SCREEN_BRIGHTNESS_MQTT_ENABLED=0
      # KIOSK_SCREEN_BRIGHTNESS_MQTT_POLL_SEC=2
      # Discover backlight names with: ls -1 /sys/class/backlight
      # KIOSK_BACKLIGHT_NAME=rpi_backlight

  - path: /usr/local/lib/kiosk-retropie/bootstrap.sh
    permissions: "0755"
    content: |
      #!/usr/bin/env bash
      set -euo pipefail

      log() { echo "kiosk-retropie bootstrap: $*" >&2; }
      die() { log "$*"; exit 1; }
      require_cmd() { command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"; }
      network_ok() { getent hosts github.com >/dev/null 2>&1 && curl -fsS https://github.com >/dev/null 2>&1; }

      main() {
        if [[ -f /var/lib/kiosk-retropie/installed ]]; then
          log "Marker present; nothing to do."
          exit 0
        fi

        require_cmd curl
        require_cmd git

        if ! network_ok; then
          die "Network not ready yet"
        fi

        local repo_url="${KIOSK_RETROPIE_REPO_URL:-}"
        local repo_ref="${KIOSK_RETROPIE_REPO_REF:-}"
        [[ -n "$repo_url" ]] || die "KIOSK_RETROPIE_REPO_URL is required"
        [[ -n "$repo_ref" ]] || die "KIOSK_RETROPIE_REPO_REF is required"

        local checkout_dir="${KIOSK_RETROPIE_CHECKOUT_DIR:-/opt/kiosk-retropie}"
        if [[ ! -d "$checkout_dir/.git" ]]; then
          log "Cloning $repo_url -> $checkout_dir"
          rm -rf "$checkout_dir"
          git clone --no-checkout "$repo_url" "$checkout_dir"
        fi

        log "Fetching ref $repo_ref"
        git -C "$checkout_dir" fetch --depth 1 origin "$repo_ref"
        git -C "$checkout_dir" checkout -f FETCH_HEAD

        if [[ ! -x "$checkout_dir/scripts/install.sh" ]]; then
          die "Installer not found or not executable: $checkout_dir/scripts/install.sh"
        fi

        exec "$checkout_dir/scripts/install.sh"
      }

      main "$@"

  - path: /etc/systemd/system/kiosk-retropie-install.service
    permissions: "0644"
    content: |
      [Unit]
      Description=kiosk-retropie one-time installer
      Wants=network-online.target
      After=network-online.target
      ConditionPathExists=!/var/lib/kiosk-retropie/installed

      [Service]
      Type=oneshot
      EnvironmentFile=-/etc/kiosk-retropie/config.env
      ExecStart=/usr/local/lib/kiosk-retropie/bootstrap.sh
      Restart=on-failure
      RestartSec=30
      StartLimitIntervalSec=0

      [Install]
      WantedBy=multi-user.target

runcmd:
  - [bash, -lc, "apt-get update && apt-get install -y --no-install-recommends ca-certificates curl git"]
  - [bash, -lc, "systemctl daemon-reload"]
  - [bash, -lc, "systemctl enable --now kiosk-retropie-install.service"]
